# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 742e76fa62b18fc368f6bc232224738ddc42b602f49cc2cce9877af74a868c4b0200407d996b9287fcd3d820fab7a401dca8a105f78964a132c130c82bf94905

test:
  secret_key_base: 86006aff62a3d9ae0bba40acf8334476fbb9a898a942069beeb73295d9ff4347678bdcefcf29c71d392ee181c66587401c85a4967acdfa632531a7e664b5765a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
